# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53abef52a280bc32386e40b4e91fac93bb93bfc02e49749f087dd4044c78abb6a3d729457dc70a458f252c79ef6fb86f8c8eaada5e348c8bf12a7f898efd8d0c

test:
  secret_key_base: a1b14d9aeaa5d98108196bcffdd38db2064e87f3396205890a6f76285655a4b77d91d36f3da53fb64f2485dbf5ea3603e65610ebe36ebd66c098b9ce80f4d437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
